// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBymfCfMDotLwIERDxPeRo3CjL1kwH5DMc',
    appId: '1:1072272390210:web:68e38a446055775c4255db',
    messagingSenderId: '1072272390210',
    projectId: 'pantry-port',
    authDomain: 'pantry-port.firebaseapp.com',
    storageBucket: 'pantry-port.firebasestorage.app',
    measurementId: 'G-KJQTGFFYJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp-uHhXfvHWVmAg6IkLTg8aH5hIZZ2_i8',
    appId: '1:1072272390210:android:9ac58ebbe8a9a5ce4255db',
    messagingSenderId: '1072272390210',
    projectId: 'pantry-port',
    storageBucket: 'pantry-port.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVmT8Ff-1g77EyHLonb6eJ9r_osM7tk6E',
    appId: '1:1072272390210:ios:303f5daf42ea39054255db',
    messagingSenderId: '1072272390210',
    projectId: 'pantry-port',
    storageBucket: 'pantry-port.firebasestorage.app',
    iosBundleId: 'com.example.pantryportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVmT8Ff-1g77EyHLonb6eJ9r_osM7tk6E',
    appId: '1:1072272390210:ios:303f5daf42ea39054255db',
    messagingSenderId: '1072272390210',
    projectId: 'pantry-port',
    storageBucket: 'pantry-port.firebasestorage.app',
    iosBundleId: 'com.example.pantryportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBymfCfMDotLwIERDxPeRo3CjL1kwH5DMc',
    appId: '1:1072272390210:web:c14edc03bc6036d44255db',
    messagingSenderId: '1072272390210',
    projectId: 'pantry-port',
    authDomain: 'pantry-port.firebaseapp.com',
    storageBucket: 'pantry-port.firebasestorage.app',
    measurementId: 'G-7K6G6ZSRDF',
  );
}
